services:
    api:
        build:
            context: .
            dockerfile: Bookstore.Infrastructure/API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=5000
        ports:
            - "5000:5000"
            - "5001:5001"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        networks:
            - bookstore-network
        depends_on:
            - mssql
            - redis
    
    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            SA_PASSWORD: iLuvBooks4ever<3
            ACCEPT_EULA: "Y"
        ports:
            - "1401:1433"
        volumes:
            - ./mssql:/var/opt/mssql/data
        networks:
            - bookstore-network
    
    redis:
        image: redis:latest
        container_name: redisdb
        restart: always
        ports:
          - "6379:6379"
        volumes:
          - ./redis-data:/data
        networks:
          - bookstore-network

networks:
    bookstore-network:
        driver: bridge